import { Roboto } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import ImportBsJS from "./components/importBsjs";

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <style>{`
            body {
              font-family: ${roboto};
            }
          `}</style>
      </head>
      <body className={roboto.className}>
        <ImportBsJS/>
        {children}
        </body>
    </html>
  );
}
